# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_longReads_wrappers", use_symbols = TRUE, package_name = "longReads")

#' @usage NULL
#' @useDynLib longReads, .registration = TRUE
NULL

#' Return string `"Hello world!"` to R.

hello_world <- function() .Call(wrap__hello_world)

#' Return string `"Hello world!"` to R.

add <- function(x, y) .Call(wrap__add, x, y)

#' Return string `"Hello world!"` to R.

analyze_fastq <- function(file_path, min_length, min_avg_qual) .Call(wrap__analyze_fastq, file_path, min_length, min_avg_qual)

#' produces a dataframe of all the reads, min length and GC content under a certain threshold.
#' @export
analyze_fastq_r <- function(file_path, min_length, min_avg_qual, min_gc_content) .Call(wrap__analyze_fastq_r, file_path, min_length, min_avg_qual, min_gc_content)


# nolint end
