# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_longReads_wrappers", use_symbols = TRUE, package_name = "longReads")

#' @usage NULL
#' @useDynLib longReads, .registration = TRUE
NULL

#' Analyze a FASTQ file and return per-read statistics
#'
#' # Arguments
#' * `file_path` - Path to the FASTQ file
#' * `min_length` - Optional minimum read length filter
#' * `min_avg_qual` - Optional minimum average Q-score filter
#' * `min_gc_content` - Optional minimum GC content filter
analyze_fastq_r <- function(file_path, min_length, min_avg_qual, min_gc_content) .Call(wrap__analyze_fastq_r, file_path, min_length, min_avg_qual, min_gc_content)


# nolint end
